/**
 * 
 * @authors dong (you@example.org)
 * @date    2016-12-26 10:57:22
 * @version $Id$
 */

/* vuex mutations定义 */

/* 首页home */
export const HOME_GET_BANNERDATA_SUCCESS = "HOME_GET_BANNERDATA_SUCCESS";
export const HOME_GET_CATEGORYDATA_SUCCESS = "HOME_GET_CATEGORYDATA_SUCCESS";
export const HOME_GET_GUIDDATA_SUCCESS = "HOME_GET_GUIDDATA_SUCCESS";
export const HOME_GET_DEALDATA_SUCCESS = "HOME_GET_DEALDATA_SUCCESS";

/* 套餐详情 */
export const DEALDETAIL_GET_DEALDETAILINFO_SUCCESS = "DEALDETAIL_GET_DEALDETAILINFO_SUCCESS";
export const DEALDETAIL_GET_DEALDETAILCOMMENTS_SUCCESS = "DEALDETAIL_GET_DEALDETAILCOMMENTS_SUCCESS";
export const DEALDETAIL_GET_DEALDETAILRECOMMENDDATA_SUCCESS = "DEALDETAIL_GET_DEALDETAILRECOMMENDDATA_SUCCESS";
export const DEALDETAIL_GET_DEALDETAILADDATA_SUCCESS = "DEALDETAIL_GET_DEALDETAILADDATA_SUCCESS";